import {
  NAVIGATION_BUTTON_CHANGE_MODE,
  NAVIGATION_BUTTON_TOGGLE,
  NAVIGATION_BUTTON_HIDE,
  NAVIGATION_BUTTON_SHOW,
  NAVIGATION_BUTTON_UPDATE_ACTION,
  NAV_BUTTON_CONFIG_SELECTOR_SAVE,
  NAV_BUTTON_CONFIG_SELECTOR_SAVE_SUCCESS,
  NAV_BUTTON_CONFIG_SELECTOR_SAVE_FAIL,
} from './types';

